-- ==========================================
-- SKEMA DATABASE: WEB KEAMANAN SISTEM INFORMASI
-- Platform: Supabase (PostgreSQL)
-- ==========================================

-- 1. TABEL UTAMA: KEAMANAN INFORMASI
CREATE TABLE IF NOT EXISTS public.keamanan_informasi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_pengguna VARCHAR(100),
    kategori_data VARCHAR(100),
    status_enkripsi VARCHAR(50),
    level_akses VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABEL METADATA BERKAS (Terhubung dari Website Vercel)
CREATE TABLE IF NOT EXISTS public.file_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    access_token TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. MENGAKTIFKAN ROW LEVEL SECURITY (RLS)
ALTER TABLE public.keamanan_informasi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.file_metadata ENABLE ROW LEVEL SECURITY;
