-- File: supabase.sql
-- Skema Tabel Keamanan Sistem Informasi

CREATE TABLE keamanan_informasi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_pengguna VARCHAR(100) NOT NULL,
    nama_berkas VARCHAR(255) NOT NULL,
    kategori_data VARCHAR(100),
    status_enkripsi VARCHAR(50),
    level_akses VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Aktifkan Row Level Security (RLS)
ALTER TABLE keamanan_informasi ENABLE ROW LEVEL SECURITY;
